# -*- coding: utf-8 -*-
"""RK_4th_order.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SVNHqtXBPbNMBnaaOy-YsNsCUVm90lt5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# dx = f(t,x) dt

def f(t, x):
  return x/t + np.cos(t)

t0, tn = 1, 10    # interval of t
x0 = 1            # initial value
h = 0.1           # step-size
n = (tn - t0)/h

t = [t0]
x = [x0]
ti = t0
xi = x0
for i in range(int(np.ceil(n))):
  k1 = h * f(ti, xi)
  k2 = h * f(ti + h/2, xi + k1/2)
  k3 = h * f(ti + h/2, xi + k2/2)
  k4 = h * f(ti + h, xi + k3)
  xi += (k1 + 2*k2 + 2*k3 + k4)/6
  ti += h
  t.append(ti)
  x.append(xi)
solution = pd.DataFrame({'t': t, 'x': x})
print(solution)
print()

plt.plot(t, x)
plt.xlabel('t')
plt.ylabel('x(t)')
plt.tight_layout()
plt.show()